adding-readme
Kal2403/Hello-Microverse pull request #1
Opened 2023-04-25 12:05 UTC by Kal2403

header with title and styles.

2023-04-25 13:32 UTC, souad988 requested changes
Hi @Kal2403 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966](https://user-images.githubusercontent.com/59707859/234286748-a53a802d-feb3-48bf-af3c-c01558b6c8b2.gif)


## Highlights
✔Use microverse template for README
✔Ignore requested file and folder
✔Add html and css files  
✔Use of correct github workflow

## Required Changes ♻️
_Great job so far 💪 consider the following changes : 

- [ ] adding file x is not a meaningful PR title please change it and always use a title that describes the overall work done in the feature exp: setup linters/add basic html css files ...
- [ ] PR description also should list more in detail but briefly headlines of what was added ,changed or optimized
- [ ]  concerning README file I'm not able to review it and add inline comments as you didn't change it in the last commit kindly change it's title to the title of this project and remove default text under each section as it was added to guide you in the content to put , do this before requesting the next review to let the next reviewer comment on it 
- [ ] Finally linters files are missing in your project kindly follow the steps in the link [html-css linter setup](https://github.com/microverseinc/linters-config/tree/master/html-css) to setup linters and make sure to correct errors before requesting review as your linter checks should be green in github  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 14:11 UTC, usorfaitheloho requested changes
Hi @Kal2403  :thumbsup:  ,

This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are still some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

## Highlights
- Linters are installed and are passing
- Good use of JavaScript, HTML&CSS best practices ✔️ 
-  Well-structured files ✔️
<br/>
<br/>
<br/>

 ## Required Changes  :recycle: 
- As suggested by the previous review, please always use descriptive PR title and write a good description in the summary 
for example 
Title - Hello world project
Description 

In this PR, i did the following :
-  Added HTML and CSS files 
- Added node_modules and test.md to .gitignore file
etc
`

_Check the comments under the review for more required changes._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 14:11 UTC, usorfaitheloho commented on README.md
>  > Describe your project in 1 or 2 sentences.
You did a great job using the required Microverse README template and editing its content, however, i'd suggest you remove descriptions from your README file as they are only meant to give you a guideline on what is expected from you in each section. Kindly remove those descriptions from all sections of your code 😄

2023-04-26 14:11 UTC, usorfaitheloho commented on README.md
>  > Describe the tech stack and include only the relevant sections that apply to your project.
You did a great job using the required Microverse README template and editing its content, however, i'd suggest you remove descriptions from your README file as they are only meant to give you a guideline on what is expected from you in each section. Kindly remove those descriptions from all sections of your code 😄

2023-04-26 14:11 UTC, usorfaitheloho commented on README.md
>  <!-- Features -->
You did a great job using the required Microverse README template and editing its content, however, i'd suggest you remove comments as well from your README file as they are only meant to give you a guideline on what is expected from you in each section. Kindly remove those comments from all sections of your code 😄

2023-04-26 14:11 UTC, usorfaitheloho commented on README.md
> +> and also keeps the working pace clean
You did a great job using the required Microverse README template and editing its content, however, i'd suggest you remove descriptions from your README file as they are only meant to give you a guideline on what is expected from you in each section. Kindly remove those descriptions from all sections of your code 😄 .Descriptions always start with `>`

2023-04-26 14:11 UTC, usorfaitheloho commented on README.md
>  > Mention all of the collaborators of this project.
You did a great job using the required Microverse README template and editing its content, however, i'd suggest you remove descriptions from your README file as they are only meant to give you a guideline on what is expected from you in each section. Kindly remove those descriptions from all sections of your code 😄

2023-04-26 14:11 UTC, usorfaitheloho commented on README.md
>  This project is [MIT](./LICENSE) licensed.
You did a great job using the required Microverse README template and editing its content, however, i'd suggest you remove descriptions from all your README file as they are only meant to give you a guideline on what is expected from you in each section. Kindly remove those descriptions from all sections of your code 😄 . Descriptions usually starts with`>`

2023-04-26 19:52 UTC, Kal2403 commented on README.md
>  > Describe your project in 1 or 2 sentences.
I have a question, so give me this for make changes.
"As suggested by the previous review, please always use descriptive PR title and write a good description in the summary
for example."
What I don't understand is. I have to edit my commit or just do better the nex commit I do?

2023-04-26 20:13 UTC, usorfaitheloho commented on README.md
>  > Describe your project in 1 or 2 sentences.
Don't edit your comment,make the required changes and then commit them

2023-04-27 07:49 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @Kal2403 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-04-27 08:12 UTC, merged